# Generated by Django 5.1.6 on 2025-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamravarsityapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
